version: '3'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - ahs-net
    depends_on:
      - nginx
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - ahs-net
    depends_on:
      - nginx  

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - ahs-net


networks:
  ahs-net:
    driver: bridge